# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Reorder rows and columns of a dense matrix with the same ordering
#'
#' @param Y A dense square matrix
#' @param sigma An integer vector that is a permutation of 0, 1, ..., ncol(Y)-1
#' @export
reorder_dense <- function(Y, sigma) {
    .Call(`_dagsbm_reorder_dense`, Y, sigma)
}

#' Reorder rows and columns of a sparse matrix with the same ordering
#'
#' @param Y A sparse square matrix
#' @param sigma An integer vector that is a permutation of 0, 1, ..., ncol(Y)-1
#' @export
reorder_sparse <- function(Y, sigma) {
    .Call(`_dagsbm_reorder_sparse`, Y, sigma)
}

#' MCMC sampler of DAG-SBM, with possible model selection between finite and infinite regime
#'
#' @param Y A sparse square matrix
#' @param sigma An integer vector that is a permutation of 0, 1, ..., ncol(Y)-1
#' @param scalars Data frame of 1 row with the following columns: K, seed, iter, thin, burn, freq, node, scan, L, pg, p_fin, mean_k, a_gamma, b_gamma, a_theta, b_theta, a_alpha, b_alpha, a1, b1, aa0, ba0, ab0, bb0, axi, bxi, ak, bk, dag, print
#' @export
mcmc_dagsbm <- function(Y, sigma, scalars) {
    .Call(`_dagsbm_mcmc_dagsbm`, Y, sigma, scalars)
}

