# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Reorder rows and columns of a dense matrix with the same ordering
#'
#' @param Y A dense square matrix
#' @param sigma An integer vector that is a permutation of 0, 1, ..., ncol(Y)-1
#' @export
reorder_dense <- function(Y, sigma) {
    .Call(`_dagsbm_reorder_dense`, Y, sigma)
}

